events {}

http {
    server {
        listen 80;
        server_name ${DOMAIN}.nip.io;

        return 301 https://$host$request_uri;

    }
    server {
        listen 443 ssl;
        server_name ${DOMAIN}.nip.io;

        ssl_certificate /etc/letsencrypt/live/${DOMAIN}.nip.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}.nip.io/privkey.pem;

        location / {
            proxy_pass http://travel-site:80;
        }
    }
}
