---

name: My First CI pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if index.html exists
        run: |
          if [ ! -f index.html ]; then
            echo "❌ index.html not found!"
            exit 1
          else
            echo "✅ index.html exists"
          fi
      
      - name: Basic HTML Check
        run: |
          if ! grep -q "<html>" index.html; then
            echo "❌ Missing <html> tag"
            exit 1
          fi

      - name: Check title exists
        run: |
          if ! grep -q "<title>" index.html; then
            echo "❌ Missing title"
            exit 1
          fi
